/* ============================================================
   VIDYA STEM – Export Module
   js/export.js  |  v3.0.0

   exportMgr.toImage(auditId)   – saves PNG of audit report
   exportMgr.toExcel(auditId)   – saves CSV (no external lib)
   ============================================================ */

const exportMgr = (() => {

  const STATUS_COLOR = APP_CONFIG.statusColors;

  /* ── Generate audit report HTML canvas via DOM ── */
  function buildReportHTML(expanded) {
    const { meta, results } = expanded;
    const d = new Date(meta.ts);
    const dateStr = d.toLocaleString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true
    });

    const present = results.filter(r => r.status === 'Well Present').length;
    const broken  = results.filter(r => r.status === 'Broken').length;
    const missing = results.filter(r => r.status === 'Missing').length;
    const total   = results.length;

    const rows = results.map((r, i) => {
      const bg = r.status === 'Well Present' ? '#e6f9f5'
               : r.status === 'Broken'       ? '#fff3e6'
               : '#fde8ea';
      const dot = r.status === 'Well Present' ? '#2a9d8f'
                : r.status === 'Broken'       ? '#f4a261'
                : '#e63946';
      return `<tr style="background:${bg}">
        <td style="padding:6px 12px;color:#555;font-size:12px">${i+1}</td>
        <td style="padding:6px 12px;font-family:monospace;font-size:12px;color:#333">${r.code}</td>
        <td style="padding:6px 12px;font-size:13px;color:${dot};font-weight:600">${r.status}</td>
      </tr>`;
    }).join('');

    return `
<div id="export-report" style="
  font-family: 'Segoe UI', sans-serif;
  background: #fff;
  padding: 32px;
  width: 600px;
  border-radius: 16px;
  box-shadow: 0 4px 32px rgba(0,0,0,0.12);
">
  <div style="display:flex;align-items:center;gap:16px;margin-bottom:24px;border-bottom:2px solid #f0f0f0;padding-bottom:16px">
    <div style="width:48px;height:48px;background:#2a9d8f;border-radius:12px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:22px;font-weight:700">V</div>
    <div>
      <div style="font-size:20px;font-weight:700;color:#1a1a2e">VIDYA STEM</div>
      <div style="font-size:12px;color:#888">Inventory Audit Report</div>
    </div>
    <div style="margin-left:auto;text-align:right">
      <div style="font-size:12px;color:#888">${dateStr}</div>
      <div style="font-size:13px;font-weight:600;color:#333">${meta.school || meta.user}</div>
    </div>
  </div>

  <div style="font-size:16px;font-weight:700;color:#1a1a2e;margin-bottom:12px">${meta.labName}</div>

  <div style="display:flex;gap:12px;margin-bottom:20px">
    <div style="flex:1;background:#e6f9f5;border-radius:10px;padding:12px;text-align:center">
      <div style="font-size:24px;font-weight:700;color:#2a9d8f">${present}</div>
      <div style="font-size:11px;color:#555">Well Present</div>
    </div>
    <div style="flex:1;background:#fff3e6;border-radius:10px;padding:12px;text-align:center">
      <div style="font-size:24px;font-weight:700;color:#f4a261">${broken}</div>
      <div style="font-size:11px;color:#555">Broken</div>
    </div>
    <div style="flex:1;background:#fde8ea;border-radius:10px;padding:12px;text-align:center">
      <div style="font-size:24px;font-weight:700;color:#e63946">${missing}</div>
      <div style="font-size:11px;color:#555">Missing</div>
    </div>
    <div style="flex:1;background:#f5f5f5;border-radius:10px;padding:12px;text-align:center">
      <div style="font-size:24px;font-weight:700;color:#333">${total}</div>
      <div style="font-size:11px;color:#555">Total</div>
    </div>
  </div>

  <table style="width:100%;border-collapse:collapse;border-radius:8px;overflow:hidden">
    <thead>
      <tr style="background:#1a1a2e;color:#fff">
        <th style="padding:8px 12px;font-size:12px;text-align:left;font-weight:500">#</th>
        <th style="padding:8px 12px;font-size:12px;text-align:left;font-weight:500">Item Code</th>
        <th style="padding:8px 12px;font-size:12px;text-align:left;font-weight:500">Status</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div style="margin-top:20px;text-align:center;font-size:11px;color:#bbb">
    Generated by VIDYA STEM Inventory System · ${dateStr}
  </div>
</div>`;
  }

  /* ── PNG export via html2canvas ── */
  async function toImage(auditId) {
    const expanded = dataStore.expandAudit(auditId);
    if (!expanded) return ui.toast('Audit not found', 'error');

    ui.toast('Generating image…', 'info');

    const container = document.createElement('div');
    container.style.cssText = 'position:fixed;left:-9999px;top:0;z-index:-1';
    container.innerHTML = buildReportHTML(expanded);
    document.body.appendChild(container);

    const el = container.querySelector('#export-report');

    // Use html2canvas if available, else fallback
    if (typeof html2canvas !== 'undefined') {
      const canvas = await html2canvas(el, { scale: 2, backgroundColor: '#f5f5f5' });
      const link = document.createElement('a');
      link.download = `audit_${expanded.meta.school || expanded.meta.user}_${expanded.meta.labName}_${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      ui.toast('Image exported!', 'success');
    } else {
      // Fallback: print
      const w = window.open('', '_blank');
      w.document.write(`<html><body style="margin:0;padding:20px;background:#f0f0f0">${container.innerHTML}</body></html>`);
      w.document.close();
      w.print();
      ui.toast('Opened print dialog', 'info');
    }
    document.body.removeChild(container);
  }

  /* ── CSV export (no external lib) ── */
  function toExcel(auditId) {
    const expanded = dataStore.expandAudit(auditId);
    if (!expanded) return ui.toast('Audit not found', 'error');

    const { meta, results } = expanded;
    const d = new Date(meta.ts).toLocaleString('en-IN');

    const rows = [
      ['VIDYA STEM – Audit Report'],
      ['School', meta.school || meta.user],
      ['Lab', meta.labName],
      ['Date', d],
      ['Auditor', meta.user],
      [],
      ['#', 'Item Code', 'Status'],
      ...results.map((r, i) => [i + 1, r.code, r.status]),
      [],
      ['Summary'],
      ['Total', results.length],
      ['Well Present', results.filter(r => r.status === 'Well Present').length],
      ['Broken', results.filter(r => r.status === 'Broken').length],
      ['Missing', results.filter(r => r.status === 'Missing').length]
    ];

    const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url  = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `audit_${meta.school || meta.user}_${Date.now()}.csv`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
    ui.toast('CSV exported!', 'success');
  }

  return { toImage, toExcel, buildReportHTML };
})();
